### ISSUE TITLE
本地弹幕载入错乱

### ISSUE THREAD

**Issue by Goshin** [AncientLysine/BiliLocal#50]
**文件名中的英文句号引起的弹幕匹配错乱。**

重现，有文件如下：

Name.E01.mkv
Name.E01.xml
Name.E02.mkv
Name.E02.xml

播放 Name.E02.mkv 时，错误载入 Name.E01.mkv 的弹幕，去掉英文句号后正常。

**Comment by AncientLysine** [comment]
应该已经正常，重新试验时记得先清除播放列表中的记录

**Comment by xylcbd** [comment]
仍然有这个问题
