### ISSUE TITLE
求问ubuntu下要装什么依赖？

### ISSUE THREAD

**Issue by boyguyue** [AncientLysine/BiliLocal#53]
xubuntu15
vlc  ffmpeg  qt5base qtcreator 已装

make显示
make
g++ -c -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DBACKEND_VLC -DRENDER_RASTER -DRENDER_OPENGL -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o APlayer.o src/Player/APlayer.cpp
In file included from src/Player/APlayer.cpp:32:0:
src/Player/VPlayer.h:8:21: fatal error: vlc/vlc.h: 没有那个文件或目录
 #include <vlc/vlc.h>
                     ^
compilation terminated.
Makefile:717: recipe for target 'APlayer.o' failed
make: *** [APlayer.o] Error 1

小白求帮助

**Comment by AncientLysine** [comment]
ubuntu需要libvlc-dev

**Comment by boyguyue** [comment]
谢谢回复！
装完后又安装了libavutil-dev libswscale-dev libvlccore-dev
继续make成功
但打开bililocal时出错
./BiliLocal
段错误 (核心已转储)

**Comment by AncientLysine** [comment]
vlc插件位置不对，把vlc/plugins拷贝到编译出的bililocal可执行文件所在目录下

**Comment by Twopothead** [comment]
[libVLC not initializing on Ubuntu 18.04 (WSL 2.0)](https://stackoverflow.com/questions/58982323/libvlc-not-initializing-on-ubuntu-18-04-wsl-2-0)
For anyone looking, fixed this. The other solutions mentioned a plugins folder for windows. Similar plugins are needed for linux. The easiest way to get them is to just do `sudo apt-get install vlc`. Then start your app and it should just work.

我也在ubuntu18.04遇到段错误，虽然已经安装libvlc-dev但还是libvlc依赖有问题，`sudo apt-get install vlc`这之后，bililocal可以正常使用了。
