### ISSUE TITLE
账号登录问题

### ISSUE THREAD

**Issue by y917059177y** [AncientLysine/BiliLocal#57]
已经很久不能登录了，不知道是不是个例，希望大大能够升级一下逻辑

**Comment by y917059177y** [comment]
具体是，输完账号密码验证码后点击登录按钮会弹出提示窗口，有个黄色感叹号加"<src“这个字符串。

**Comment by leeraymond78** [comment]
改了api了吧

**Comment by y917059177y** [comment]
应该是的

**Comment by AncientLysine** [comment]
@y917059177y 以下提交已经修复登录问题，不过没有正式发布版本
424e1f543ac5316d0cacbc840d1be0a1767e72d5
9c785719f914087c446dfb42b13e770799aac345
可以在网盘的Unstable目录下找到最新开发版试用
