### ISSUE TITLE
qt5.6.1编译出错

### ISSUE THREAD

**Issue by 107nationalstation** [AncientLysine/BiliLocal#58]
/usr/include/qt/QtCore/qhashfunctions.h:101: error: no matching function for call to 'qHash(const AtlasMgr::CreateInfo&)'
     Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))
     ^

**Comment by AncientLysine** [comment]
前几天在本地Android分支上修了，稍后上传。最近Master上的提交都只在VS上验过……

**Comment by AncientLysine** [comment]
#60 master合了
