### ISSUE TITLE
[BUG] 从播放列表中打开视频后，无法通过鼠标操作窗口

### ISSUE THREAD

**Issue by wanzzhehe** [AncientLysine/BiliLocal#69]
我在从BiliLocal的播放列表中打开视频后，关闭列表，然后发现无法通过鼠标来操作窗口，可以用鼠标双击退出全屏，但是无法移动窗口，最小化、最大化和关闭窗口，Alt+F4也无法使用，但是软件快捷键正常。
系统：Windows 10 1803
版本：0.4.2

**Comment by zdfcg** [comment]
迟来的解决方法：把DandanPlay插件禁用
貌似这个插件会触发bug
